language: node_js

node_js:
- 0.10

sudo: false

env:
  global:
    secure: "UY7ndcaw/AVY7HMtLWb9Pj47I5yaiPgJJlER4XW1PirXpH/iZar9J9Ud7vcAWTIfjGdJprwOuKqgSm1hUOSlxD1M+FcO6OkIFU6HGS+VQ7Z94/UlkOVZciwzxL4i7uDYp772xMdzTtKmab54bBGPgWTac4dcz1AWbmSUu4WsyxQ="

cache:
  directories:
    - bower_components
    - node_modules

before_script:
- node_modules/.bin/bower install --config.interactive=false

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/afc2f5d920cef69671db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
